# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dennis Pitman
email: dpitman@dennis-pitman.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome!  I'm a former music student, recovering lawyer, and self-taught developer-in-training.
  This blog is where I hope to share my progress as I learn more about web development,
  and share my experience trying new tools, tutorials, and techniques.  I'll also
  write about legal topics that catch my eye and seem relevant to tech, music, or
  general web culture.  As I grow as a developer, I'll also share some of my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dpitman85.github.io" # the base hostname & protocol for your site
twitter_username: @Dennis_Pitman
github_username:  dpitman85

# Build settings
markdown: kramdown
